site_name: kubernetes/OpenShift Security & Demo and More.
site_url: https://ralvares.github.io/security-demos/
repo_name: ralvares/security-demos
repo_url: https://github.com/ralvares/security-demos
docs_dir: use_cases

theme:
  name: material

# This maps your folder structure to the navigation bar
nav:
  - Home: 'README.md'
  - Modules:
    - Module 1 - Architecture, Threats & Security Strategy: 
        - OpenShift Security Architecture & Threat Awareness: 'compliance/architecture and threat awareness.md'
        - The 10 Essential Controls - A Unified Kubernetes Security Playbook: 'compliance/README.md'
        - The 8 Pillars of a Secure Container Platform: 'compliance/the 8 pillars of a secure container platform.md'
        - The Risk-Driven Business Conversation: 'compliance/The Risk-Driven Business Conversation.md'
    - Module 2 - Secure Multi-Tenancy & Project Governance: 
        - Multi-Tenancy: 'rbac/multi-tenancy.md'
        - Automated Project Provisioning: 'rbac/project-demo.md'
    - Module 3 - Identity and Access Management: 
        - RBAC Fundamentals: 'rbac/rbac-intro.md'
        - Granular Custom Roles: 'rbac/custom-roles.md'
    - Module 4 - Admission Control & Enforcement: 
        - IAM and Admission Control Overview: 'admissioncontrols/README.md'
        - Resource Quotas: 'admissioncontrols/quota.md'
        - Cluster-Wide Quotas: 'admissioncontrols/ClusterResourceQuota.md'
        - LimitRanges: 'admissioncontrols/limits.md'
        - Security Context Constraints (SCC): 'admissioncontrols/scc.md'
        - Validating Admission Policy (VAP) Overview: 'admissioncontrols/vap/README.md'
        - Validating Admission  Demo: 'admissioncontrols/vap/vap-demo.md'
    - Module 5 - Network Security & Isolation: 
        - Network Policies Intro: 'networking/README.md'
        - Network Policies - Demo: 'networking/networkpolicies/protecting-the-network-using-networkpolicies.md'
        - Admin Network Policies Intro: 'networking/networkpolicies/adminnetworkpolicies.md'
        - AdminNetworkPolicies - Demo: 'networking/networkpolicies/anp-demo.md'
    - Module 6 - Compliance: 
        - Compliance Operator Demo: 'compliance/compliance-operator-demo.md'
        - Compliance Operator Variables: 'compliance/compliance-operator-variables.md'
    - Module 7 - Incident Response & Forensics: 
        - Mastering Audit Logs & Forensics: 'auditing/audit-log-Investigation.md'
        - Kubectl Timemachine: 'auditing/kubectl-timemachine-instructions.md'
    - Module 8 - Sovereign:
        - Sovereign Cloud Overview: 'sovereign.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition

