apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
  name: corporate-access-external-networks-guardrail
spec:
  priority: 12
  subject:
    namespaces:
      matchLabels:
        security.allow/networks: "true"
  egress:
    - name: allow-corporate-external-networks
      action: Allow
      to:
        - networks:
            - 95.216.68.119/32    # corporate-vpn-1.corp.example.com
      ports:
        - portNumber:
            protocol: TCP
            port: 443
