apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Replaced 'commonLabels' with 'labels'
labels:
  - pairs:
      app.kubernetes.io/part-of: vap-examples
      app.kubernetes.io/managed-by: kustomize
      custom.security/enforce: "true"
      pod-security.kubernetes.io/enforce: "privileged"
      pod-security.kubernetes.io/enforce-version: "latest"

resources:
  - dev-team-namespace.yaml
  - finance-app-namespace.yaml
  - platform-ops-namespace.yaml