apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pipeline-demo
resources:
- namespace.yaml
- serviceaccount-pipeline.yaml
- rhacs-image-check.yaml
- rhacs-image-scan.yaml
- rhacs-deployment-check.yaml
- rhacs-simple-demo-pipeline.yaml
