apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: image-supply-chain-scan
  namespace: openshift-compliance
profiles:
  - name: image-supply-chain-checks
    kind: TailoredProfile
    apiGroup: compliance.openshift.io/v1alpha1
settingsRef:
  name: default
  kind: ScanSetting
  apiGroup: compliance.openshift.io/v1alpha1
