apiVersion: policy.networking.k8s.io/v1alpha1
kind: BaselineAdminNetworkPolicy
metadata:
  name: default
spec:
  subject:
    namespaces:
      matchLabels:
        custom.security/enforce: "true"
  ingress:
  - name: "deny-all-ingress"
    action: "Deny"
    from:
    - namespaces: {} # Denies all cluster-internal traffic
  egress:
  - name: "deny-all-egress"
    action: "Deny"
    to:
    - namespaces: {} # Denies all cluster-internal traffic