
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-team-a-default-8080
  namespace: team-b
spec:
  podSelector:
    matchLabels:
      app: default
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: team-a
        podSelector:
          matchLabels:
            app: default
      ports:
        - protocol: TCP
          port: 8080
---
