apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: sensitive-pod-security-checks
  namespace: openshift-compliance
spec:
  title: Sensitive Pod Security Checks
  description: Custom checks for sensitive hostPath mounts and privileged pods.
  enableRules:
    - name: detect-sensitive-hostpath-mounts
      kind: CustomRule
      rationale: Detect sensitive hostPath mounts
    - name: detect-privileged-pods
      kind: CustomRule
      rationale: Detect privileged pods and hostPID usage
    - name: detect-token-automount
      kind: CustomRule
      rationale: Detect service account token automount
