apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-store
  namespace: loki-audit
spec:
  resources:
    requests:
      storage: 10G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce